### ISSUE TITLE
Toon with Google Assistant

### ISSUE THREAD

**Issue by joostvanmourik** [cyberjunky/home-assistant-custom-components#13]
Should it be possible to use Toon with the Google Assistant. If i ask OK Google whats the temperature. It says the current temperature but also says toon is Off

There is no way to activate it. And if i like to change te temperature it seems not to recognize the command.

Any idea ?

**Comment by RudolfRendier** [comment]
This component should handle intents:
https://developers.home-assistant.io/docs/en/intent_handling.html

In the meantime you should be able to do it yourself by using conversation/intent scripts:
https://www.home-assistant.io/components/conversation/
https://www.home-assistant.io/components/intent_script/

**Comment by Webserve** [comment]
This is also a wish for me.  tried to do this with the conversation but with no success

**Comment by joostvanmourik** [comment]
Still on the todo list :-)

**Comment by Webserve** [comment]
For small workarround:
use the generic_thermostat in home assistant.

**Comment by joostvanmourik** [comment]
For the built-in Toon component there was an issue regarding the state. This issue is already fixed: https://github.com/home-assistant/home-assistant/pull/18966 4 Will be in the next release i think. Maybe the custom component has the same issue?

**Comment by michel130** [comment]
I have the same problem, this weekend I installed home assistant and when I ask OK Google whats the temperature. It says the current temperature but also says toon is Off

There is no way to activate it. And if i like to change the temperature for example 18 degrees it says I could not find this, it is not there.

**Comment by Webserve** [comment]
@michel130 create a generic termostat component and sync this with the toon termostat. In the google assistant you can exclude the toon thermostat. 

```yaml
climate:
  - platform: toon
    name: Toon Thermostaat
    host: 192.168.10.13
    port: 10080
    scan_interval: 8
  - platform: generic_thermostat
    name: verwarming
    heater: switch.power
    target_sensor: sensor.toon_temperatuur
    min_temp: 13
    max_temp: 23
```

```yaml
sensor:
  - platform: template
    sensors:
      toon_temperatuur:
        friendly_name: "Toon Temeperatuur"
        unit_of_measurement: '°C'
        value_template: "{{states.climate.toon_thermostaat.attributes.current_temperature}}"
  - platform: template
    sensors:
      toon_temperatuur_gezet:
        friendly_name: "Toon Temeperatuur Gezet"
        unit_of_measurement: '°C'
        value_template: "{{states.climate.toon_thermostaat.attributes.temperature}}"
  - platform: template
    sensors:
      verwarming_temperatuur:
        friendly_name: "Verwarming Temeperatuur"
        unit_of_measurement: '°C'
        value_template: "{{states.climate.verwarming.attributes.current_temperature}}"
  - platform: template
    sensors:
      verwarming_temperatuur_gezet:
        friendly_name: "Verwarming Temeperatuur Gezet"
        unit_of_measurement: '°C'
        value_template: "{{states.climate.verwarming.attributes.temperature}}"

automation:
  - trigger:
      platform: homeassistant
      # Event can also be 'shutdown'
      event: start
    action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.verwarming
        temperature: "{{states.sensor.toon_temperatuur_gezet.state}}"
  
  - trigger:
      platform: state
      entity_id: sensor.toon_temperatuur_gezet
    condition:
      condition: template
      value_template: "{{ state_attr('climate.toon_thermostaat', 'temperature') != state_attr('climate.verwarming', 'temperature') }}"
    action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.verwarming
        temperature: "{{states.sensor.toon_temperatuur_gezet.state}}"
  
  - trigger:
      platform: state
      entity_id: sensor.verwarming_temperatuur_gezet
    condition:
      condition: template
      value_template: "{{ state_attr('climate.toon_thermostaat', 'temperature') != state_attr('climate.verwarming', 'temperature') }}"
    action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.toon_thermostaat
        temperature: "{{states.sensor.verwarming_temperatuur_gezet.state}}"

````

and in the google assistant config:

```yaml

    climate.toon_thermostaat:
      expose: false

```

**Comment by cyberjunky** [comment]
Great stuff. I was trying to see if the original toon component fixes which were done lately -and were referred too in this post- fixed it for my custom component, but didn't get it to improve, still not sure what google misses, Will try above, and also try to fix the custom component with this info.

**Comment by michel130** [comment]
@Webserve thanks for your nice instruction.

I am only stuck with one thing:

I add climate - sensor - automation in the following file: configuration.yaml

But when I add this in the configuration.yaml under my google assistant
climate.toon_thermostaat:
      expose: false

I received an error. 
Do I also need to delete the files what I download from this site?

**Comment by Webserve** [comment]
https://www.home-assistant.io/components/google_assistant/ <- 

I dont know the error. But read the docs. 
Also you can try to expose both to google assistant and see if thats working.

**Comment by michel130** [comment]
@cyberjunky did you get it working?
I could say hey google set temperature on 20 degrees, it says okay I will set Toon on 20 degrees but on  Toon nothing has changed, but when I check the Home Assistant I see that it did but not on Toon.

When I used your toon.py and change it manual in the Home Assistant it changed also on Toon, only not the one from Webserve.

In this case yours can do manual in Home Assistant but not wit google home.
The one from Webserve is working with google home, but does not change it on Toon self.

Thanks, 

Regards,
Michel

**Comment by cyberjunky** [comment]
I have the temperature change function working now in a very rough version of toon.py.
Still need to work on the modes, will try to get this working tomorrow.

![capture _2018-12-10-22-54-14](https://user-images.githubusercontent.com/5447161/49764329-67850200-fccf-11e8-9201-ff0259116aab.png)

**Comment by joostvanmourik** [comment]
Wow great work. IF you need somebody to test i'am free this evening :-)

**Comment by michel130** [comment]
@cyberjunky nice work, if you want I also can also test it.. :

**Comment by joostvanmourik** [comment]
> I have the temperature change function working now in a very rough version of toon.py.
> Still need to work on the modes, will try to get this working tomorrow.
> 
> ![capture _2018-12-10-22-54-14](https://user-images.githubusercontent.com/5447161/49764329-67850200-fccf-11e8-9201-ff0259116aab.png)

Any Progress ?

**Comment by cyberjunky** [comment]
Not really.. Google assistant only supports a few modes. I guess operation mode will be pinned to heating. And we can only toggle program on off. Working with commands that are completely different than the modes of toon is not logical. I'm trying to combine this with the correct commands displayed in gui like we had without google ass. Support. Toon is simply not a normal climate device with on off heat cool

**Comment by joostvanmourik** [comment]
> Not really.. Google assistant only supports a few modes. I guess operation mode will be pinned to heating. And we can only toggle program on off. Working with commands that are completely different than the modes of toon is not logical. I'm trying to combine this with the correct commands displayed in gui like we had without google ass. Support. Toon is simply not a normal climate device with on off heat cool

If we can set program on/of and it goes back to the latest programmed mode would be usable for me.

**Comment by cyberjunky** [comment]
Yes thats want i want to achieve. It took some time to figure out how other climate devices do this. But their commands fit better.. And i discovered that after i defined min and max temp inside the component you can ask google to set the themostat higher or lower.. It will add/substract 5c of current set temp.

**Comment by llewy** [comment]
Any chance that you upload the last version of your component? I don't actually need the programs on Toon, I use Home Assistant to set the temperature, based on some automations. Would be 'cool' to talk to my GH and let it set the temperature to a certain degree though.

**Comment by michel130** [comment]
The same here, I only want to ask to google home, what is the temperature in the house, and than say okay google set temperature on for example 22 degrees .

**Comment by createthisnl** [comment]
Sounds like great progress! Will it be possible to define the on and off states to one of the operation modes from Toon in the configuration.yaml/customize.yaml? Or should does it need to be some fixed values? 

Something like
```yaml
climate:
 - platform: toon name: Toon Thermostaat
    host: 192.168.10.99
    port: 10080
    scan_interval: 7
    on_preset: 0 # 0=Comfort. If not defined, defaults to 1 (Home) 
    off_preset: 4 # 4=Holiday. If not defined, defaults to 3 (Away)
```
