### ISSUE TITLE
Add the boiler-status information as sensor for Home-Assistant

### ISSUE THREAD

**Issue by Emacee** [cyberjunky/home-assistant-custom-components#5]
As discussed from this post on:
[Toon app: boiler status](https://www.domoticaforum.eu/viewtopic.php?f=87&t=11671&start=45) the Toon is able to display the status of an OpenTherm boiler. If it would be possible to incorporate this data in Home-Assistant the need for an OpenTherm Gateway is taken away since you will be able to log and monitor the behaviour of your boiler more closely.

**Comment by cyberjunky** [comment]
Yeah I'm following that thread and want to add support for it as well, but it's yet unclear to me how to install the toon app, I rather install the separate tool, not an app store.... is that possible?

**Comment by Emacee** [comment]
Since I wasn't sure enough to root the Toon myself I bought one that was rooted already and came with the ToonStore installed. Must say, the ToonStore is really convenient. 

For future reference, this is the first version of code that was [posted](https://www.domoticaforum.eu/viewtopic.php?f=87&t=11671&start=75#p85063):
```
- platform: rest
  name: Boiler Status
  json_attributes:
    - sampleTime
    - boilerSetpoint
    - roomTempSetpoint
    - boilerPressure
    - roomTemp
    - boilerOutTemp
    - boilerInTemp
    - boilerModulationLevel
  resource: http://toon/boilerstatus/boilervalues.txt
  value_template: '{{ value_json.sampleTime }}'

```

The issue with that is that the sensor is sampleTime with all the values as attribute rather than different sensors with as attribute the sample time. I will look into the Home-Assistant docs to see whether that is an easy fix. Don't have any development experience so far so can't promise anything. 

P.S. Created this Home-Assistant meets Toon load screen for the Toon to display something nice on startup. 
![loadscreen-toon](https://user-images.githubusercontent.com/29025081/35471129-aa8d2e34-0355-11e8-8407-4405bdff1664.png)

**Comment by Emacee** [comment]
Whoa that was easy, this way it works as sensor. Would this be possible to incorporate it into a component so you would only have to set TOON-IP choose which sensors you would want? Or is that not the way it works? 

```
- platform: rest
    name: Boiler Status
    json_attributes:
      - sampleTime
      - boilerSetpoint
      - roomTempSetpoint
      - boilerPressure
      - roomTemp
      - boilerOutTemp
      - boilerInTemp
      - boilerModulationLevel
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.sampleTime }}'
  - platform: rest
    name: Boiler Pressure
    json_attributes:
      - sampleTime
      - boilerSetpoint
      - boilerModulationLeve
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.boilerPressure }}'
    unit_of_measurement: bar
  - platform: rest
    name: Boiler setpoint
    json_attributes:
      - sampleTime
      - boilerSetpoint
      - boilerPressure
      - boilerModulationLevel
      - roomTemp
      - roomTempSetpoint
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.boilerSetpoint }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: Boiler In Temperature
    json_attributes:
      - sampleTime
      - boilerOutTemp
      - boilerInTemp
      - boilerSetpoint
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.boilerInTemp }}'
    unit_of_measurement: "°C"
  - platform: rest
    name: Boiler Out temperature
    json_attributes:
      - sampleTime
      - boilerOutTemp
      - boilerInTemp
      - boilerSetpoint
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.boilerOutTemp }}'
    unit_of_measurement: "°C"
- platform: rest
    name: Boiler modulation level
    json_attributes:
      - sampleTime
      - boilerSetpoint
    resource: http://TOON-IP/boilerstatus/boilervalues.txt
    value_template: '{{ value_json.boilerModulationLevel }}'
    unit_of_measurement: "%"
```

Result looks like this: 

<img width="373" alt="schermafbeelding 2018-01-27 om 11 49 14" src="https://user-images.githubusercontent.com/29025081/35471274-24b73d9c-0358-11e8-8677-2980c9911014.png">
